### ISSUE TITLE
Tareas con edificios sin alturas

### ISSUE THREAD

**Issue by JorgeSanzS** [OSM-es/CatAtomWeb#2]
No se porque sucede pero me ha pasado ya en 2 o 3 tareas que salen todos los edificios sin importar las alturas de los edificios.
Al principio creía que era un error puntual y lo arregle a mano pero ya me resulta raro.
Me ha pasado en esta
https://catastro.openstreetmap.es/results/37119/tasks/9464001QE0896S.osm.gz
En este caso en verdad son como 2 zonas, los de arriba a la izquierda si salen las alturas pero los de abajo a la derecha no salen. En los otros casos que me ha pasado era la tarea entera.

**Comment by JorgeSanzS** [comment]
Otro en el que pasa
https://catastro.openstreetmap.es/results/37119/tasks/9363303QE0896S.osm.gz

**Comment by javiersanp** [comment]
No tengo ordenador para mirarlo. ¿Dices que no le pasa a una parte del
edificio, sino a todo? Y en el wms si sale información de alturas (los
números romanos?

**Comment by JorgeSanzS** [comment]
Pasa al edificio completo. Es un pueblo que la mayoría directamente no tienen partes, al ser la mayoría casas unitarias. Pero las pocas que deberían tener partes a diferentes alturas, no está tampoco dibujada la geometría de cada altura diferente.

En el segundo que he pasado no hay ninguna geometría con building:levels

En la capa wms si sale la información de alturas.

Sin prisa que ya leí que ibas a estar un poco desconectado. Lo deje por aquí para que no se perdiera.

**Comment by javiersanp** [comment]
Pues le pongo un marcador y si no, recuérdamelo.

Saludos

**Comment by JorgeSanzS** [comment]
Añado otro que es en un proyecto diferente
https://catastro.openstreetmap.es/results/37056/tasks/6031708PF8263S.osm.gz

**Comment by javiersanp** [comment]
Hola
Los archivos ATOM que usaste eran de fecha 2022-03-12, Catastro ha actualizado a 2022-09-23.
Al usar los archivos recientes ya no pasa el problema, lo que hace pensar que el fallo venía de origen en los datos.
Saludos.
